language: python
python:
  - "3.5"
# command to run tests
install:
  - pip install python-coveralls
  - pip3 install termcolor
  - pip install coverage
script:
  - make test
  - coverage run -m unittest
after-success:
  - coveralls
